"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"         # https://{organization-name}.crowdin.com for Crowdin Enterprise

"files": [
  {
    "source": "/src/cards/de/*.md",                                       #source files filter
    "translation": "/src/cards/%two_letters_code%/%original_file_name%"        #where translations are stored
  },
  {
    "source": "/src/rules/rules.de.md",                                       #source file filter
    "translation": "/src/rules/rules.%two_letters_code%.md"                   #where translations are stored
  }
]